version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sztu_check?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root_123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - ./articles:/app/uploadFile/
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root_123
      MYSQL_DATABASE: sztu_check
    volumes:
      - ./mysql_data:/var/lib/mysql  # 将MySQL的数据目录挂载到当前目录的mysql_data文件夹
      - ./mysql.conf:/etc/mysql/mysql.conf
    ports:
      - "3307:3306" # 将MySQL容器的端口映射到主机的3307端口

  redis:
    image: redis:latest
    ports:
      - "6380:6379" # 将Redis容器的端口映射到主机的6380端口
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 将 Nginx 容器的 80 端口映射到主机的 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 将你的 nginx.conf 文件映射到容器内的 Nginx 配置路径
      - /root/naive-check-frontend:/usr/share/nginx/frontend
    depends_on:
      - backend
