/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    apply {
        id("org.springframework.boot") version "2.6.7"
        id("io.spring.dependency-management") version "1.1.3"
    }
}

repositories {
    maven {
        url = uri("https://maven.aliyun.com/repository/public/")
    }
    mavenCentral()
}

dependencies {
    api("javax.xml.bind:jaxb-api:2.4.0-b180830.0359")
    api("org.springframework.boot:spring-boot-starter-parent:2.6.7")
    api("org.springframework.boot:spring-boot-starter-data-redis:2.6.7")
    api("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.0.1")
    api("com.alibaba:druid-spring-boot-starter:1.1.9")
    api("org.springframework.boot:spring-boot-starter-web:2.6.7")
    api("org.springframework.boot:spring-boot-starter:2.6.7")
    api("com.baomidou:mybatis-plus-boot-starter:3.5.3.2")
    api("mysql:mysql-connector-java:8.0.28")
    api("org.jetbrains:annotations:24.0.1")
    api("org.projectlombok:lombok:1.18.20")
    annotationProcessor("org.projectlombok:lombok:1.18.20")
    api("org.aspectj:aspectjweaver:1.9.7")
    api("com.alibaba:fastjson:1.2.83")
    api("io.jsonwebtoken:jjwt:0.6.0")
    api("org.apache.commons:commons-lang3:3.10")
    api("cn.hutool:hutool-all:5.8.22")
    api("com.github.pagehelper:pagehelper:5.3.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.7")
}

group = "com.sztu.sztu_check"
version = "1.0-SNAPSHOT"
description = "sztu_check"
java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

