/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        maven {
            url = uri("https://maven.aliyun.com/repository/gradle-plugin")
        }
    }
}
rootProject.name = "sztu_check"
